@startuml
class Users {
    {field} id: uuid
    {field} name: string
    {field} tax_id: string
    {field} email: string
    {field} password: hash
    {field} created_at: timestamp
    {field} is_active: boolean
    {method} create()
    {method} read_all()
    {method} read_one()
    {method} update_one()
    {method} delete_one()
}

class Company {
    {field} id: uuid
    {field} name: name
    {field} tax_id: string
    {field} email: string
    {field} password: hash
    {field} created_at: timestamp
    {field} is_active: boolean
    {method} create()
    {method} read_all()
    {method} read_one()
    {method} update_one()
    {method} delete_one()
}

class Jobs {
    {field} id: uuid
    {field} user_id: uuid
    {field} company_id: uuid
    {field} external_id: string
    {field} role: string
    {field} created_at: timestamp
    {field} last_update: timestamp
    {field} is_active: boolean
    {method} create()
    {method} read_all()
    {method} read_one()
    {method} update_one()
    {method} delete_one()
}

@enduml